services:
  - type: web
    name: zuolian-kb
    env: python
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /
    buildCommand: pip install --upgrade pip && pip install -r requirements.render.txt
    startCommand: cd "app/frontend" && streamlit run app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
